### ISSUE TITLE
Gallery problems with Feb. 18 release

### ISSUE THREAD

**Issue by halatmit** [mit-cml/appinventor-sources#710]
@wolberd @jisqyv 

These two reports might be the same issue:

On Thu, Feb 18, 2016 at 11:23 PM, Italo Barbiero italobarbiero@gmail.com wrote:
    After a search in the gallery, when clicking on "more apps" it repeats the same 10 apps that are already showing.

Scott Ferguson:
I cannot find any of my apps in the gallery.
A corrupted index, perhaps?
They already disappeared once before and I had to add them back

**Comment by jisqyv** [comment]
I'm looking through the logs. It looks like we are getting
StatusCode.TRANSIENT_ERROR back from the Google Search API and instead of
retrying, we are de-referencing a null pointer, which causes a 500 error to
be returned to the client. The red error only is visible for a short while,
so some people may not notice the error and just notice that the gallery
operation didn't seem to do anything.

The code in question is in GallerySearchIndex.java at line 157. That line
references size.t which will be null if the error on line 152 is
experienced. Of course the code doesn't log if that error is happening on
line 152, so we cannot know for sure, but I believe that is what is going
on.

Of course this is all being brought on by Google signalling the
TRANSIENT_ERROR, which I suspect they have only recently been sending us.

-Jeff

On Friday, February 19, 2016, hal <notifications@github.com> wrote:

> @wolberd <https://github.com/wolberd> @jisqyv <https://github.com/jisqyv>
>
> These two reports might be the same issue:
>
> On Thu, Feb 18, 2016 at 11:23 PM, Italo Barbiero italobarbiero@gmail.com
> <javascript:_e(%7B%7D,'cvml','italobarbiero@gmail.com');> wrote:
> After a search in the gallery, when clicking on "more apps" it repeats the
> same 10 apps that are already showing.
>
> Scott Ferguson:
> I cannot find any of my apps in the gallery.
> A corrupted index, perhaps?
> They already disappeared once before and I had to add them back
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mit-cml/appinventor-sources/issues/710>.
>


-- 
_______________________________________________________________________
Jeffrey I. Schiller
Information Systems and Technology – MIT App Inventor
Massachusetts Institute of Technology
77 Massachusetts Avenue  Room 32-386
Cambridge, MA 02139-4307
617.910.0259 - Voice
jis@mit.edu
http://jis.qyv.name
http://appinventor.mit.edu
_______________________________________________________________________

**Comment by wolberd** [comment]
Hi everyone. Thomas has fixed at least the error about clicking next on
search results. I've cc'd him here. I don't think his changes have been
merged yet.

Dave

On Fri, Feb 19, 2016 at 11:36 AM, Jeffrey Schiller <notifications@github.com
> wrote:

> I'm looking through the logs. It looks like we are getting
> StatusCode.TRANSIENT_ERROR back from the Google Search API and instead of
> retrying, we are de-referencing a null pointer, which causes a 500 error to
> be returned to the client. The red error only is visible for a short while,
> so some people may not notice the error and just notice that the gallery
> operation didn't seem to do anything.
>
> The code in question is in GallerySearchIndex.java at line 157. That line
> references size.t which will be null if the error on line 152 is
> experienced. Of course the code doesn't log if that error is happening on
> line 152, so we cannot know for sure, but I believe that is what is going
> on.
>
> Of course this is all being brought on by Google signalling the
> TRANSIENT_ERROR, which I suspect they have only recently been sending us.
>
> -Jeff
>

**Comment by jisqyv** [comment]
@wolberd I see two changes from Thomas. I don't believe either of them addresses this issue.

**Comment by toropeza** [comment]
@jisqyv @wolberd 
Hi Jeff,
I fixed this issue on this pull request that has already been merged into the source code. Has it been deployed into the current live version? If so my changes did not fix this issue. I linked my changes below.
Thanks, Thomas
https://github.com/mit-cml/appinventor-sources/commit/5e05b2e4d43a36f9aac9a43f6fb049322f67757b

**Comment by jisqyv** [comment]
@toropeza @wolberd It has been deployed. It doesn't fix this issue. Look at my previous comment "The code in question is in GallerySearchIndex.java at line 157..." You have a comment about retrying, but no code to do so. Well, the transient errors are happening. The code falls through and we get a NPF.

**Comment by ewpatton** [comment]
This looks like it was fixed with 7f6a457b85.
